version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
  AfterInstall:
    - location: scripts/change_permission.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600
  ValidateService:
    - location: scripts/stop_server.sh
      timeout: 3600
      runas: ec2-user
